jwt:
  secret: 'Kocia@szajkA^i**ZaGaDka123!Znikn--iec90(iasle$$d&z][i'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/usersapplication
    password: user123!
    username: usersapplication
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

